name: Run commands on different operating systems
on: [push]

jobs:
  Run-npm-on-Ubuntu:
    name: Run docker Ubuntu
    runs-on: ubuntu-latest
    
    steps:
      - name: Run a test 
    #  - uses: terraform-hw/hw-create-ecs1@main
        run: |
          git clone https://github.com/terraform-hw/hw-create-ecs1.git
          cd hw-create-ecs1
          ls -l 
          wget -O - https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update && sudo apt install terraform
          terraform plan 
          terraform apply
