name: Run commands on different operating systems
on:
  push:
    branches: [ main ]

jobs:
  Run-npm-on-Ubuntu:
    name: Run docker Ubuntu
    runs-on: ubuntu-latest
    
    steps:
      - name: Run a test 
      - uses: terraform-hw/hw-create-ecs1@main
      - run: |
           terraform --version 
