name: Run commands on different operating systems
on: [push]

jobs:
  Run-npm-on-Ubuntu:
    name: Run docker Ubuntu
    runs-on: ubuntu-latest
    
    steps:
      - name: Run a test 
    #  - uses: terraform-hw/hw-create-ecs1@main
        run: |
          git clone https://github.com/terraform-hw/hw-create-ecs1.git
          cd hw-create-ecs1
          ls -l 
          terraform --version 
